In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv('https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv')
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61469,ZWE,Africa,Zimbabwe,2021-01-17,27203.0,322.0,818.000,713.0,30.0,29.429,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.535
61470,ZWE,Africa,Zimbabwe,2021-01-18,27892.0,689.0,799.286,773.0,60.0,35.000,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.535
61471,ZWE,Africa,Zimbabwe,2021-01-19,28675.0,783.0,776.571,825.0,52.0,39.143,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.535
61472,ZWE,Africa,Zimbabwe,2021-01-20,29408.0,733.0,736.000,879.0,54.0,41.429,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.535
61473,ZWE,Africa,Zimbabwe,2021-01-21,30047.0,639.0,668.429,917.0,38.0,40.143,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.535

In [3]:
# 全球確診人數最高的一天


print("全球確診人數最高的一天：")

fliter = (df["location"] == "World")
y=df[fliter].new_cases.idxmax(skipna=True)
df.iloc[[y]]

全球確診人數最高的一天：

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
60554,OWID_WRL,NaN,World,2021-01-07,88105210.0,856352.0,659538.143,1898021.0,14354.0,11383.571,...,15469.207,10.0,233.07,8.51,6.434,34.635,60.13,2.705,72.58,NaN

In [4]:
#df.plot(kind='line',x='date', y=['new_cases'] , xlim=0 ,rot=20)
#plt.show( )

In [5]:
#找出確診國家中，12月新增確診成長率最高、最低的三個國家


df["date"] = pd.to_datetime(df["date"])  
mask = (df["date"] >= '2020-11-01') & (df["date"] <= '2020-11-30')
#print(df.loc[mask])

sector = df.loc[mask].groupby("iso_code")
nov = sector.new_cases.sum( )

maskk = (df["date"] >= '2020-12-01') & (df["date"] <= '2020-12-31')
sectorr = df.loc[maskk].groupby("iso_code")
dec = sectorr.new_cases.sum( )


import numpy as np

rate = (dec-nov).div(nov)
rate[np.isinf(rate)] = np.nan                               # 排除除數為零的情況
print("12月新增確診成長率最高的三個國家：")
print(rate.nlargest(5))                                       # 排前五名檢查同數值並列第三名的可能
print("\n")
print("12月新增確診成長率最低的三個國家：")
print(rate.nsmallest(5))

#驗算
#n=sector.get_group('MHL').new_cases.sum( )
#d=sectorr.get_group('MHL').new_cases.sum( )
#print(d-n/n)

12月新增確診成長率最高的三個國家：
iso_code
THA    13.084821
BFA     8.898964
SUR     7.238532
NAM     5.616609
GRD     5.615385
Name: new_cases, dtype: float64


12月新增確診成長率最低的三個國家：
iso_code
MHL   -1.000000
SLB   -1.000000
VUT   -1.000000
WSM   -1.000000
DMA   -0.914286
Name: new_cases, dtype: float64